spec:
  replicas: 1
  imagePullSecrets: ""

environment: ""

config:
  otel:
    exporterOtlpEndpoint: ""
  connectionStrings:
    postgres: ""
    storageAccount: ""
  jwt:
    audience: ""
    authority: ""
  serviceUrls:
    storageAccount: ""
  imageProcessing: 
    {
    }