name: 'Build and push helm chart'

on:
  workflow_call:
    inputs:
      environment:
        description: 'Github Environment'
        required: true
        type: string
      acr_name:
        description: 'Azure Container Registry Name'
        required: true
        default: 'tliscr'
        type: string
      container_name:
        description: 'Container Name'
        required: true
        type: string
    secrets:
      CONTAINER_REGISTRY_USERNAME:
        description: 'Azure Container Registry Username'
        required: true
      CONTAINER_REGISTRY_PASSWORD:
        description: 'Azure Container Registry Password'
        required: true

jobs:
  build-helm-chart-and-push:
      name: 'Build helm chart and push'
      environment: ${{ inputs.environment }}
      runs-on: ubuntu-latest
      steps:
      # checkout the repo
      - name: 'Checkout Github Action'
        uses: actions/checkout@v3
      # install helm
      - name: 'Install helm'
        uses: Azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # login to Azure Container Registry
      - name: 'Login to acr using helm'
        run: |
          echo $ | helm registry login ${{ inputs.acr_name }}.azurecr.io --username ${{ secrets.CONTAINER_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      # package and push the chart
      - name: 'Package chart'
        run: cd chart && helm package . --app-version ${{ github.sha }}
      # push the chart
      - name: 'Push chart'
        run: cd chart && helm push ${{ inputs.container_name }}-* oci://${{ inputs.acr_name }}.azurecr.io/helm