name: 'Build and push image'

on:
  workflow_call:
    inputs:
      environment:
        description: 'Github Environment'
        required: true
        type: string
      acr_name:
        description: 'Azure Container Registry Name'
        required: true
        default: 'tliscr'
        type: string
      container_name:
        description: 'Container Name'
        required: true
        type: string
    secrets:
      CONTAINER_REGISTRY_USERNAME:
        description: 'Azure Container Registry Username'
        required: true
      CONTAINER_REGISTRY_PASSWORD:
        description: 'Azure Container Registry Password'
        required: true

jobs:
  build-container-and-push:
    name: 'Build container and push to ACR'
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3
    # login to Azure Container Registry
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ inputs.acr_name }}.azurecr.io
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    # build and push the image
    - run: |
        docker build . --file api.Dockerfile --tag ${{ inputs.acr_name }}.azurecr.io/${{ inputs.container_name }}:${{ github.sha }}
        docker push ${{ inputs.acr_name }}.azurecr.io/${{ inputs.container_name }}:${{ github.sha }}
        docker build . --file cli.Dockerfile --tag ${{ inputs.acr_name }}.azurecr.io/${{ inputs.container_name }}-cli:${{ github.sha }}
        docker push ${{ inputs.acr_name }}.azurecr.io/${{ inputs.container_name }}-cli:${{ github.sha }}